FROM jguillaumes/simh-allsims
MAINTAINER Jordi Guillaumes Pons <jg@jordi.guillaumes.name>

ENV PATH /simh-bin:$PATH
ENV SIMULATOR pdp11
ENV SIMDIR pdp11v7
ENV OSIMAGE RP04.000.gz

VOLUME /machines
WORKDIR /machines
RUN cp /simh-bin/$SIMULATOR /machines/$SIMULATOR && \
    rm /simh-bin/* && \
    mv /machines/$SIMULATOR /simh-bin && \
    mkdir /image

EXPOSE 2323-2324

WORKDIR /image
COPY /$SIMDIR/$OSIMAGE       /image/
COPY /$SIMDIR/*.txt          /image/
COPY /$SIMDIR/$SIMULATOR.ini /image/
COPY /$SIMDIR/startup.sh     /startup.sh
COPY /$SIMDIR/original-content /machines

WORKDIR /machines

ENTRYPOINT ["/startup.sh"]
