FROM jguillaumes/simh-allsims
MAINTAINER Jordi Guillaumes Pons <jg@jordi.guillaumes.name>

ENV PATH /simh-bin:$PATH

WORKDIR /workdir
RUN cp /simh-bin/pdp11 . && rm /simh-bin/* && cp pdp11 /simh-bin


EXPOSE 2323
EXPOSE 2324
VOLUME /machines

WORKDIR /machines
COPY /pdp11bsd/pdp11.ini /machines
COPY /pdp11bsd/RA81.000.gz /machines
COPY /pdp11bsd/startup.sh /startup.sh 

ENTRYPOINT ["/startup.sh"]

