FROM debian:latest
MAINTAINER Jordi Guillaumes Pons <jg@jordi.guillaumes.name>

ENV BUILDPKGS "git gcc make libvdeplug2-dev"
ENV RUNPKGS "net-tools vde2 libvdeplug2 nano libpcap-dev"

RUN apt-get update && apt-get install -y ${RUNPKGS} 

WORKDIR /workdir

RUN apt-get update && apt-get install -y ${BUILDPKGS} && \ 
	git clone git://github.com/simh/simh.git && \
	cd simh && make && \
	mkdir /simh-bin && cp BIN/* /simh-bin && \
	apt-get purge --yes --auto-remove ${BUILDPKGS} 

ENV PATH /simh-bin:$PATH

EXPOSE 2323
EXPOSE 2324
EXPOSE 2325

VOLUME /machines
WORKDIR /machines

RUN rm -rf /workdir

