FROM debian:latest
ARG sims="vax vax780 pdp11 pdp8 vax8600 pdp10"
ARG version="3.1-debian" 

LABEL version="$version"
LABEL description="Selected SIMH simulators"
LABEL maintainer="Jordi Guillaumes Pons <jguillaumes@gmail.com>"

ENV BUILDPKGS "gcc git libvdeplug-dev libbluetooth-dev make"
ENV RUNPKGS "net-tools vde2 libvdeplug2 nano"

RUN apt-get update

WORKDIR /workdir

RUN apt-get install -y libc6-dev libpcap-dev && \
    apt-get install -y $RUNPKGS  && \
    apt-get install -y $BUILDPKGS && \
    git clone --depth 1 --single-branch git://github.com/simh/simh.git && \
    cd simh && \
    make $sims && \
    mkdir /simh-bin && cp -r BIN/* /simh-bin && \
    apt-get remove -y $BUILDPKGS && \
    apt-get remove -y gcc && \
    apt-get clean -y && \
    apt-get autoremove -y && \
    rm -rf /workdir 

ENV PATH /simh-bin:$PATH

EXPOSE 2323-2326

VOLUME /machines
WORKDIR /machines

ENTRYPOINT ["bash"]
