FROM debian:latest
ARG sims="vax vax780 pdp11 pdp8 vax8600 pdp10"

MAINTAINER Jordi Guillaumes Pons <jg@jordi.guillaumes.name>

ENV BUILDPKGS "gcc git libvdeplug-dev libbluetooth-dev make"
ENV RUNPKGS "net-tools vde2 libvdeplug2 nano"

RUN apt-get update

WORKDIR /workdir

COPY /deb/libpcap0.8-dev_1.8.1-3.nobt_amd64.deb /workdir/
COPY /deb/libpcap0.8_1.8.1-3.nobt_amd64.deb	/workdir/

RUN apt-get install -y libc6-dev && \
    dpkg -i libpcap0.8-dev_1.8.1-3.nobt_amd64.deb libpcap0.8_1.8.1-3.nobt_amd64.deb && \
    apt-get install -y $RUNPKGS  && \
    apt-get install -y $BUILDPKGS && \
    git clone git://github.com/simh/simh.git && \
    cd simh && \
    make -j 2 $sims && \
    mkdir /simh-bin && cp BIN/* /simh-bin && \
    apt-get remove -y $BUILDPKGS && \
    apt-get remove -y gcc && \
    apt-get clean -y && \
    apt-get autoremove -y && \
    rm -rf /workdir 

ENV PATH /simh-bin:$PATH

EXPOSE 2323-2326

VOLUME /machines
WORKDIR /machines

ENTRYPOINT ["bash"]
