FROM jguillaumes/simh-base
MAINTAINER Jordi Guillaumes Pons <jg@jordi.guillaumes.name>

WORKDIR /workdir

RUN cd simh && \
    git pull && \
    make pdp11 && \
    cp BIN/* /simh-bin

ENV PATH /simh-bin:$PATH

EXPOSE 2323
RUN mkdir /machines
VOLUME /machines

WORKDIR /machines
COPY /pdp11bsd/pdp11.ini /machines
COPY /pdp11bsd/RA81.000.gz /machines
COPY /pdp11bsd/startup.sh /startup.sh 

ENTRYPOINT ["/startup.sh"]

