FROM jguillaumes/simh-allsims
MAINTAINER Jordi Guillaumes Pons <jg@jordi.guillaumes.name>

ENV PATH /simh-bin:$PATH

WORKDIR /workdir
RUN cp /simh-bin/vax780 . && rm /simh-bin/* && cp vax780 /simh-bin

EXPOSE 2323
EXPOSE 2324

VOLUME /machines

WORKDIR /machines
COPY /vaxbsd/vax780.ini /machines
COPY /vaxbsd/boot42 /machines
COPY /vaxbsd/RA81.000.gz /machines
COPY /vaxbsd/startup.sh /startup.sh 

ENTRYPOINT ["/startup.sh"]
