FROM jguillaumes/simh-allsims
MAINTAINER Jordi Guillaumes Pons <jg@jordi.guillaumes.name>

ENV PATH /simh-bin:$PATH
ENV SIM vax8600
ENV SIMDIR vaxnbsd
ENV OSIMAGE  RAUSER000.vhd.gz
ENV EMPIMAGE RAUSEREMP.vhd.gz

WORKDIR /workdir
RUN cp /simh-bin/$SIM . && \
    rm /simh-bin/* && \
    cp $SIM /simh-bin && \
    mkdir /image

EXPOSE 2323
EXPOSE 2324

WORKDIR /image
COPY /$SIMDIR/$SIM.ini	/image/
COPY /$SIMDIR/$OSIMAGE	/image/
COPY /$SIMDIR/$EMPIMAGE	/image/
COPY /$SIMDIR/*.txt    	/image/
COPY /$SIMDIR/startup.sh /startup.sh

VOLUME /machines
WORKDIR /machines
COPY /$SIMDIR/original-content /machines/

ENTRYPOINT ["/startup.sh"]
